spring:
  application:
    name: lovable-clone
    description: This is my Lovable Clone application

  datasource:
    url: jdbc:postgresql://localhost:9000/testDB
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

jwt:
  secret-key: ajkgafkjawnfasdjfawjk89rw3ekngrwvkjnfakjdfnawkejfn

stripe:
  api:
    secret: sk_test_51SpDv737ewMWNPsxG87OzkgcE1Vm9pLiLNUbnSRRSFahpkGBEhLCdRtHgmrX65CI6EP3hlerEDKtnZToVsNcWx1G00kZ0ROymV
  webhook:
    secret: whsec_571222e8698d8344d06d0e6acbd8fdc3b62d110352fe92b96ecb6e3b5b86f6f2

client.url: http://localhost:8080