spring:
  application:
    name: lovable-clone
    description: This is my Lovable Clone application

  datasource:
    url: jdbc:postgresql://localhost:9000/testDB
    username: testUser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true

jwt:
  secret-key: ajkgafkjawnfasdjfawjk89rw3ekngrwvkjnfakjdfnawkejfn

stripe:
  api:
    secret: YOUR_STRIPE_SECRET_KEY
  webhook:
    secret: YOUR_WEBHOOK_SECRET_KEY

client.url: http://localhost:8080